networks:
  frontend:
    external: true
    name: reverse-proxy

services:
  kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    volumes:
      - data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # https
      - "traefik.http.routers.uptime-kuma.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt"
    # add the network to the service configuration
    networks:
      - frontend

volumes:
  data: