networks:
  frontend:
    external: true
    name: reverse-proxy

services:
  kuma:
    image: louislam/uptime-kuma:latest
    # user: ${UID}:${GID}
    volumes:
      - data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      # http
      - "traefik.http.routers.uptime-kuma.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=web"
    # add the network to the service configuration
    networks:
      - frontend

volumes:
  data:
    driver: local